# Generated by Django 4.2.3 on 2023-08-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicesApp', '0002_userrentservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrentservice',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
