# Generated by Django 4.2.3 on 2023-08-03 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicesApp', '0003_userrentservice_returned'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(null=True)),
                ('rented_service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='servicesApp.userrentservice')),
            ],
        ),
    ]
