# Generated by Django 4.2.3 on 2023-08-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicesApp', '0004_returnrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.CharField(choices=[('rent', 'Nuomojami'), ('sale', 'Parduodami')], default='sale', max_length=5),
        ),
    ]
